"""empty message

Revision ID: 01c45b412f4c
Revises: 3c1b81461776
Create Date: 2020-07-16 21:39:39.676623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c45b412f4c'
down_revision = '3c1b81461776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'code')
    # ### end Alembic commands ###
