"""empty message

Revision ID: 1136b30f5331
Revises: bfbd08dc5983
Create Date: 2020-07-29 17:41:03.257794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1136b30f5331'
down_revision = 'bfbd08dc5983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_title', sa.String(length=30), nullable=False),
    sa.Column('menu_icon', sa.String(length=40), nullable=True),
    sa.Column('path', sa.String(length=60), nullable=True),
    sa.Column('new_item', sa.Boolean(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['menu_item.id'], name=op.f('fk_menu_item_father_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item'))
    )
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_country')
    )
    op.drop_table('menu_item')
    # ### end Alembic commands ###
