"""empty message

Revision ID: 169b2d5bb300
Revises: bb2aac339b05
Create Date: 2020-07-23 18:52:31.979311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169b2d5bb300'
down_revision = 'bb2aac339b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active_theme', sa.Integer(), nullable=True),
    sa.Column('is_dark_sidenav', sa.Boolean(), nullable=True),
    sa.Column('enable_sidebar_background_image', sa.Boolean(), nullable=True),
    sa.Column('selected_sidebar_image', sa.String(length=50), nullable=True),
    sa.Column('mini_sidebar', sa.Boolean(), nullable=True),
    sa.Column('box_layout', sa.Boolean(), nullable=True),
    sa.Column('rtl_layout', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_setting_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_setting'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setting')
    # ### end Alembic commands ###
