"""empty message

Revision ID: 21d709adeb3f
Revises: 01c45b412f4c
Create Date: 2020-07-21 18:03:22.590321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21d709adeb3f'
down_revision = '01c45b412f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent'))
    )
    op.create_table('planogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('decription', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planogram'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('sub_category', sa.String(length=40), nullable=True),
    sa.Column('brand', sa.String(length=40), nullable=True),
    sa.Column('sub_brand', sa.String(length=40), nullable=True),
    sa.Column('container', sa.String(length=40), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('planogram_id', sa.Integer(), nullable=False),
    sa.Column('start_before', sa.DateTime(), nullable=True),
    sa.Column('complete_before', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_task_agent_id_agent')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_task_customer_id_customer')),
    sa.ForeignKeyConstraint(['planogram_id'], ['planogram.id'], name=op.f('fk_task_planogram_id_planogram')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.drop_table('test')
    op.add_column('customer', sa.Column('country', sa.String(length=40), nullable=True))
    op.drop_constraint('fk_customer_country_id_country', 'customer', type_='foreignkey')
    op.drop_column('customer', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_customer_country_id_country', 'customer', 'country', ['country_id'], ['id'])
    op.drop_column('customer', 'country')
    op.create_table('test',
    sa.Column('lat1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_table('task')
    op.drop_table('product')
    op.drop_table('planogram')
    op.drop_table('agent')
    # ### end Alembic commands ###
