"""empty message

Revision ID: 28fa33f7b053
Revises: 31d51c5d12bc
Create Date: 2020-07-31 14:47:59.657907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fa33f7b053'
down_revision = '31d51c5d12bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(length=40), nullable=True))
    op.add_column('company', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'mobile_number')
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
