"""empty message

Revision ID: 49bb46f1faf8
Revises: df10331061df
Create Date: 2020-07-29 17:55:02.091259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bb46f1faf8'
down_revision = 'df10331061df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_table('menu_item_by_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_by_role_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_menu_item_by_role_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_by_role'))
    )
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_role_id_role'), 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_role_id_role'), 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('menu_item_by_role')
    op.drop_table('role')
    # ### end Alembic commands ###
