"""empty message

Revision ID: 83dd93189c3a
Revises: ade4af6396f4
Create Date: 2020-07-22 12:12:37.604467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dd93189c3a'
down_revision = 'ade4af6396f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_planogram_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planogram'))
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('planogram_id', sa.Integer(), nullable=False),
    sa.Column('start_before', sa.DateTime(), nullable=True),
    sa.Column('complete_before', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_task_agent_id_agent')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_task_customer_id_customer')),
    sa.ForeignKeyConstraint(['planogram_id'], ['planogram.id'], name=op.f('fk_task_planogram_id_planogram')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('planogram')
    # ### end Alembic commands ###
