"""empty message

Revision ID: 88a9a3c269f2
Revises: e6068e4a8417
Create Date: 2020-07-29 13:13:47.553566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a9a3c269f2'
down_revision = 'e6068e4a8417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_agent_user_id_user', 'agent', type_='foreignkey')
    op.create_foreign_key(op.f('fk_agent_company_id_company'), 'agent', 'company', ['company_id'], ['id'])
    op.drop_column('agent', 'user_id')
    op.add_column('planogram', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_planogram_user_id_user', 'planogram', type_='foreignkey')
    op.create_foreign_key(op.f('fk_planogram_company_id_company'), 'planogram', 'company', ['company_id'], ['id'])
    op.drop_column('planogram', 'user_id')
    op.add_column('product', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_product_user_id_user', 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_company_id_company'), 'product', 'company', ['company_id'], ['id'])
    op.drop_column('product', 'user_id')
    op.add_column('task', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_task_user_id_user', 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_company_id_company'), 'task', 'company', ['company_id'], ['id'])
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_task_company_id_company'), 'task', type_='foreignkey')
    op.create_foreign_key('fk_task_user_id_user', 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'company_id')
    op.add_column('product', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_product_company_id_company'), 'product', type_='foreignkey')
    op.create_foreign_key('fk_product_user_id_user', 'product', 'user', ['user_id'], ['id'])
    op.drop_column('product', 'company_id')
    op.add_column('planogram', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_planogram_company_id_company'), 'planogram', type_='foreignkey')
    op.create_foreign_key('fk_planogram_user_id_user', 'planogram', 'user', ['user_id'], ['id'])
    op.drop_column('planogram', 'company_id')
    op.add_column('agent', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_agent_company_id_company'), 'agent', type_='foreignkey')
    op.create_foreign_key('fk_agent_user_id_user', 'agent', 'user', ['user_id'], ['id'])
    op.drop_column('agent', 'company_id')
    # ### end Alembic commands ###
