"""empty message

Revision ID: a5afe184f3e9
Revises: 88a9a3c269f2
Create Date: 2020-07-29 16:36:23.426299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5afe184f3e9'
down_revision = '88a9a3c269f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol'))
    )
    op.add_column('user', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_rol_id_rol'), 'user', 'rol', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_rol_id_rol'), 'user', type_='foreignkey')
    op.drop_column('user', 'rol_id')
    op.drop_table('rol')
    # ### end Alembic commands ###
