"""empty message

Revision ID: ade4af6396f4
Revises: fdaa3966a25d
Create Date: 2020-07-21 23:30:50.137201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade4af6396f4'
down_revision = 'fdaa3966a25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_agent_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent'))
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('street_name', sa.String(length=40), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_customer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_table('planogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('decription', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_planogram_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planogram'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('upc', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('sub_category', sa.String(length=40), nullable=True),
    sa.Column('brand', sa.String(length=40), nullable=True),
    sa.Column('sub_brand', sa.String(length=40), nullable=True),
    sa.Column('container', sa.String(length=40), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_product_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('planogram_id', sa.Integer(), nullable=False),
    sa.Column('start_before', sa.DateTime(), nullable=True),
    sa.Column('complete_before', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_task_agent_id_agent')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_task_customer_id_customer')),
    sa.ForeignKeyConstraint(['planogram_id'], ['planogram.id'], name=op.f('fk_task_planogram_id_planogram')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('product')
    op.drop_table('planogram')
    op.drop_table('customer')
    op.drop_table('agent')
    # ### end Alembic commands ###
