"""empty message

Revision ID: bb2aac339b05
Revises: a3091b96c5b7
Create Date: 2020-07-23 18:28:12.739151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2aac339b05'
down_revision = 'a3091b96c5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activeTheme', sa.Integer(), nullable=True),
    sa.Column('isDarkSidenav', sa.Boolean(), nullable=True),
    sa.Column('enableSidebarBackgroundImage', sa.Boolean(), nullable=True),
    sa.Column('selectedSidebarImage', sa.String(length=50), nullable=True),
    sa.Column('miniSidebar', sa.Boolean(), nullable=True),
    sa.Column('boxLayout', sa.Boolean(), nullable=True),
    sa.Column('rtlLayout', sa.Boolean(), nullable=True),
    sa.Column('darkMode', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_setting_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_setting'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setting')
    # ### end Alembic commands ###
