"""empty message

Revision ID: d1364a41a27c
Revises: 83dd93189c3a
Create Date: 2020-07-22 13:27:25.191865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1364a41a27c'
down_revision = '83dd93189c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('height_size', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('width_size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'width_size')
    op.drop_column('product', 'height_size')
    # ### end Alembic commands ###
