"""empty message

Revision ID: df10331061df
Revises: 1136b30f5331
Create Date: 2020-07-29 17:45:37.579684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df10331061df'
down_revision = '1136b30f5331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_by_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_by_rol_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_menu_item_by_rol_rol_id_rol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_by_rol'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_by_rol')
    # ### end Alembic commands ###
